"""Maintenance: added URL field and removed attachments.

Revision ID: aa9ed3e094d5
Revises: 3cb12dfd8d6e
Create Date: 2024-04-24 22:39:03.511051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9ed3e094d5'
down_revision: Union[str, None] = '3cb12dfd8d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenances', sa.Column('instructions_url', sa.String(), nullable=True))
    op.drop_column('maintenances', 'attachment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenances', sa.Column('attachment', sa.VARCHAR(), nullable=True))
    op.drop_column('maintenances', 'instructions_url')
    # ### end Alembic commands ###
