[database]
url = "sqlite:///machines-test.sqldb"
name = "fablab"

[MQTT]
broker = "localhost"
port = 1883
client_id = "backend-1"
topic = "/machine/"        # root topic. Subtopics will be /machine/<ID> will be subscribed
reply_subtopic = "/reply"  # appended to the machine topics for replies by backend. E.g. machine/1/reply
stats_topic = "/stats/"
user = "backend"

[web]
secret_key = "lkgsjòlgjsd"