[database]
url = "sqlite:///initial.db"
name = "initial"

[MQTT]
broker = "localhost"
port = 1883
client_id = "test"
topic = "machine"
reply_subtopic = "/reply"
stats_topic = "stats"

[web]
secret_key = "initial-secret"
default_admin_email = "initial@test.com"

[email]
server = "smtp.test.com"
port = 587
use_tls = true
username = "user"
password = "pass"
sender = "admin@fablab.org"
